- modules/organizations/organizations.server.model.js
Server side code for - Customisable about (accessible by leaders profile) card on trello.
Adds a new field to the database where users can optionally input their websites URL.
> new field organizationUrl added to model

- modules/issues/issue.server.model.js
Backend update for the customizable heading on the issue page. Added a new field to the mongoose issue model.
> mediaHeading field added to model

- art-baseline.yaml
- modules/issues/issue.server.model.js
- modules/issues/issues.server.controller.js
- modules/organizations/organizations.server.model.js
- modules/proposals/proposal.server.model.js
- modules/proposals/proposals.server.controller.js
- modules/solutions/solution.server.model.js
- modules/solutions/solutions.server.controller.js
- modules/suggestions/suggestion.server.model.js
- modules/suggestions/suggestions.server.controller.js
- modules/topics/topic.server.model.js
- modules/topics/topics.server.controller.js
- package-lock.json
- package.json
Soft delete properties added to models - copied the soft delete functionality from the list views to other controllers.
Created a function to handle filtering proposals `filterSoftDeleteProposals`, could not work out how to do it with mongoose query.
> Soft delete

- modules/issues/issues.server.controller.js
- modules/proposals/proposals.server.controller.js
- modules/solutions/solutions.server.controller.js
- modules/suggestions/suggestions.server.controller.js
Fix for the update requests due to organizations being an array.
> Update request fix - 400 error

- modules/issues/issue.server.model.js
- modules/issues/issues.server.controller.js
- modules/proposals/proposal.server.model.js
- modules/proposals/proposals.server.controller.js
- modules/solutions/solution.server.model.js
- modules/solutions/solutions.server.controller.js
Action/Solution/Issue  Models - imageUrl has default property that points towards asset images on client app.
> Default images

- modules/organizations/organization.validation.js
- modules/organizations/organizations.server.model.js
Model / Validation update with organization name for the "company name" issue.
> Organization Name for model

- modules/organizations/organization.validation.js
- modules/organizations/organizations.server.controller.js
- modules/organizations/organizations.server.model.js
Updated model to have a privateOrg field to handle private orgs.
Moved the API call to trigger the `read` organization route. organizationId parameter handler now checks whether a user is entering an organization url as well as an mongodb objectId.
> Invisible Communities

- modules/organizations/organizations.server.model.js
EntityId for Organization model
> Admin-login

- modules/all.server.routes.js
- modules/core/.client/app/init.js
- modules/generic.server.policy.js
- modules/issues/issues.server.controller.js
- modules/proposals/proposals.server.controller.js
- modules/solutions/solutions.server.controller.js
- modules/suggestions/suggestions.server.controller.js
- modules/topics/topics.server.controller.js
- modules/users/.client/controllers/authentication.client.controller.js
- modules/users/controllers/users.authentication.server.controller.js
- modules/users/controllers/users.profile.server.controller.js
- modules/users/controllers/users.verification.server.controller.js
Created a new middleware function on `all.server.routes.js` that checks every api call for the organization cookie. I tried to make the function in the config but I ran into mongoose error where the models were not defined yet.
Updated the list controller functions to draw the organization url from the cookie. Also added the organization cookie to the SSO oauth functions. However I wasn't sure what conditions where we didn't want the organization to be saved on the user object. So it might be added in places where it's not necessary.
> Cookie Organization Middleware

- modules/all.server.routes.js
- modules/users/controllers/users.authentication.server.controller.js
url is not present in header when redirecting from SSO so using org url cookie stored by frontend
cookie organization could be "null" as string so if statement was failign to detect it as not present
some errors while adding org to user on login for existing users
> quickfixes

- modules/all.server.routes.js
- modules/issues/issues.server.controller.js
- modules/organizations/organizations.server.controller.js
- modules/proposals/proposals.server.controller.js
- modules/solutions/solutions.server.controller.js
- modules/suggestions/suggestions.server.controller.js
- modules/topics/topics.server.controller.js
- modules/users/controllers/users.authentication.server.controller.js
- modules/users/controllers/users.profile.server.controller.js
new method to get referer
logging if failing to see referer
logging if failing to get orgUrl
updated queries to handle null organization properly
> more fixes

- modules/all.server.routes.js
- modules/generic.server.policy.js
- modules/issues/issues.server.controller.js
- modules/proposals/proposals.server.controller.js
- modules/solutions/solutions.server.controller.js
- modules/suggestions/suggestions.server.controller.js
- modules/topics/topics.server.controller.js
- modules/users/controllers/users.authentication.server.controller.js
- modules/users/controllers/users.profile.server.controller.js
added the organization object onto the request object as the cookie wasn't present on initial requests yet (was only looking at req.cookie and setting res.cookie in the middleware)
> org on request

- modules/all.server.routes.js
- modules/users/controllers/users.authentication.server.controller.js
the referer was being set as the AAF domain after SSO redirect so preferencing the cookie and then deleting it
> preferencing orgUrl cookie over referer

- modules/suggestions/suggestions.server.controller.js
Nodemailer caused the promise chain to cancel, should now error gracefully using their own error callback function.
> Suggestions Create Bug

- modules/users/controllers/users.profile.server.controller.js
- modules/users/user.server.model.js
- modules/users/users.server.routes.js
- modules/users/users.validation.js
Backend route + model updates to store the state of the app tour for the user.
> Tour - Backend

- modules/issues/issues.server.controller.js
- modules/issues/seed/seed.js
- modules/organizations/organizations.server.controller.js
- modules/proposals/proposals.server.controller.js
- modules/proposals/seed/seed.js
- modules/solutions/seed/seed.js
- modules/solutions/solutions.server.controller.js
- modules/suggestions/seed/seed.js
- modules/suggestions/suggestions.server.controller.js
- modules/topics/seed/seed.js
- modules/topics/topics.server.controller.js
On organization create the database will be seeded with default issue/action/solution/suggestion. 
Gave each Controller a seed function as well as a default seed document to populate the model. Had some issues with saving the docs and so moved the save function to each promise, can alternatively wait until all promises are returned and then async iterate over them. Might be better readability, but at least this way the promise chain isn't held up by mongodb.
> Default content

- .gitignore
- modules/organizations/organizations.server.controller.js
- modules/users/controllers/users.authentication.server.controller.js
- package-lock.json
- package.json
- server.js
Included dotenv for easy storage of config keys. 
Rewrote update, removed __v so that the database won't encounter version errors when owners update their organization.
Removed _id from req.body so mongodb doc is not overwritten.
Merged the email queries to search for existing email addresses or _id docs. (not entirely sure _id part is necessary - only needed if user objects aren't populated on the client moderator array)
Changed save rapid profile user = false redirect route.
> Organization Update

- .gitignore
- gulpfile.js
- modules/organizations/organizations.server.model.js
- modules/users/controllers/users.authentication.server.controller.js
- modules/users/user.server.model.js
- modules/votes/votes.server.controller.js
- package-lock.json
- package.json
For `feature/student-vote-lockdown`  - merging to staging
On AAF save - the aaf attributes ( https://rapid.aaf.edu.au/developers ) are saved to the `providerData` variable on the user profile.
Organization takes a new array `voteRoles` which contains a list of roles set by the front end. 
Votes now check a users `providerData` affiliation against the vote roles to see whether votes are allowed.
> Vote lockdown

- config/env/development.js
- config/env/production.js
- modules/users/controllers/users.authentication.server.controller.js
- modules/users/controllers/users.verification.server.controller.js
- modules/users/user.server.model.js
- package-lock.json
- package.json
New service implemented - check development / production config files and update env vars accordingly.
If a mobile number exists currently on the database then the backend will throw an error and now save the user.
> Twilio SMS

- modules/helpers/slug.js
- modules/issues/issue.server.model.js
- modules/issues/issue.validation.js
- modules/issues/issues.server.controller.js
- modules/proposals/proposal.server.model.js
- modules/proposals/proposals.server.controller.js
- modules/proposals/proposals.validation.js
- modules/solutions/solution.server.model.js
- modules/solutions/solutions.server.controller.js
- modules/solutions/solutions.validation.js
- modules/suggestions/suggestion.server.model.js
- modules/suggestions/suggestions.server.controller.js
- modules/suggestions/suggestions.validation.js
- modules/topics/topic.server.model.js
- modules/topics/topic.validation.js
- modules/topics/topics.server.controller.js
This reverts commit 7ec5a9ebaa567d941889841327c62badd7e28241, reversing
changes made to 85daf4a98251e00750f721b256115e94dfb3025e.
> Revert "Merge pull request #81 from NewVote/staging"

- modules/organizations/organizations.server.controller.js
requires `feature/moderator-fail-feedback` front end branch.
New function to filter the moderator emailArray coming from the client app. Returns a filtered array of strings to the client app with emails that do not exist on database.
> organization update for moderators

- modules/reps/reps.server.controller.js
- modules/reps/reps.server.model.js
- modules/reps/reps.validation.js
For latest `feature/reps` client branch
- Updated backend to return user emails that fail to be added to the database.
> Reps - Polish

- modules/reps/reps.server.controller.js
Fixes issue of all reps being returned by each community.
> Rep Search fix

- modules/notifications/notifications.server.controller.js
- modules/notifications/notifications.server.model.js
Updates to the Notification Schema to include position field as well as rep data.
> Notification Schema

- config/assets/staging.js
- config/env/default.js
- config/env/production.js
- config/env/staging.js
- config/lib/express.js
- gulpfile.js
- modules/all.server.routes.js
- modules/notifications/notifications.server.routes.js
- modules/organizations/organizations.server.routes.js
- modules/progress/progress.server.routes.js
- modules/reps/reps.server.routes.js
- modules/users/controllers/users.authentication.server.controller.js
- modules/users/strategies/jwt.js
- modules/users/users.server.routes.js
- modules/votes/votes.server.controller.js
- modules/votes/votes.server.routes.js
- package-lock.json
- package.json
- server.js
Fixes issue with cookies not appearing during SSO login callback
> SSO Login Bug

- modules/users/controllers/users.authentication.server.controller.js
Changed SSO user update to mark the `providerData` object as modified signalling mongodb to update the user object.
> SSO Verification Bug
